### ISSUE TITLE
starter如何通过属性配置在yml里面配置<dubbo:parameter>注入到applicationConfig的parameters属性

### ISSUE THREAD

**Issue by zshi456** [apache/dubbo-spring-boot-project#223]
我看源码里面只自动注入了原始类型和string

**Comment by mercyblitz** [comment]
It will be supported on next version based on new dubbo's implementation

**Comment by mercyblitz** [comment]
It works, you have to configure like :

```yml
dubbo:
    application:
        parameters[a]: b
```
