### ISSUE TITLE
[Issue] qos configuration does not work

### ISSUE THREAD

**Issue by foreveryang321** [apache/dubbo-spring-boot-project#501]
2.7.1 the same problem
```xml
<dependency>
      <groupId>org.apache.dubbo</groupId>
     <artifactId>dubbo-spring-boot-starter</artifactId>
     <version>2.7.1</version>
</dependency>
```
> the wrong configuration(The  IDEA automatic completion)
```yaml
dubbo:
  application:
    name: dubbo-spring-cloud-provider
    qos-enable: false
    qos-port: 33333
    qos-accept-foreign-ip: false
```
> the correct configuration
```yaml
dubbo:
  application:
    name: dubbo-spring-cloud-provider
    qos:
       enable: false
       port: 33333
       accept:
         foreign:
           ip: false
```
