### ISSUE TITLE
启动consumer报错qos-server can not bind localhost:22222

### ISSUE THREAD

**Issue by LBJWt** [apache/dubbo-spring-boot-project#529]
设置qos-server端口不生效，还是报端口被占用
```
qos-server can not bind localhost:22222, dubbo version: 2.7.1, current host: 192.168.2.109

java.net.BindException: Address already in use: bind
```
bootstrap.yaml配置：
```
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: spring-cloud-alibaba-dubbo-server
  application:
    qos-port: 33333
    qos-enable: true
    qos-accept-foreign-ip: false
```
