### ISSUE TITLE
zookeeper not connected

### ISSUE THREAD

**Issue by l343765828** [apache/dubbo-spring-boot-project#657]
zookeeper:3.5.5
dubbo:2.7.5
一直报：java.lang.IllegalStateException: zookeeper not connected

**Comment by lzf971107** [comment]
@l343765828 
Hello, 能否给出测试demo

**Comment by l343765828** [comment]
有邮箱吗

**Comment by l343765828** [comment]
application.yml：
```
# Spring boot application
spring:
  application:
    name: dubbo-auto-configuration-provider-demo
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: com.testzipkin.provider.service
    # Dubbo Protocol
  protocol:
    name: dubbo
    port: -1
  registry:
    address: 192.168.3.244:31217
    protocol: zookeeper
```
provider pom：
<dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.5.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.2.0</version>
        </dependency>

**Comment by lzf971107** [comment]
您可以直接将您的 demo 代码上传至 当前 issue中。
点击文本框下面  Attach files by dragging & dropping, selecting or pasting them. 即可上传文件。

**Comment by l343765828** [comment]
[zipkin.zip](https://github.com/apache/dubbo-spring-boot-project/files/4038885/zipkin.zip)

**Comment by l343765828** [comment]
@lzf971107 已上传

**Comment by lzf971107** [comment]
> @lzf971107 已上传

请稍等

**Comment by lzf971107** [comment]
@l343765828 
看起来像是 zookeeper的依赖错误导致的

将
```xml
<dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.5.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.2.0</version>
        </dependency>
``` 

替换为
```xml
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by l343765828** [comment]
能受累发个demo回来吗 我刚又测了下redis redis单体可以顺利跑 当我用redis集群做注册中心的时候 消费者找不到提供者 redis集群是三主三从

**Comment by l343765828** [comment]
@lzf971107

**Comment by lzf971107** [comment]
[zipkin.zip](https://github.com/apache/dubbo-spring-boot-project/files/4039127/zipkin.zip)

@l343765828 

注册中心的地址我改过，你记得修改下。

**Comment by l343765828** [comment]
好的 redis集群这问题 我直接给您发贴配置文件的代码吧？

**Comment by lzf971107** [comment]
redis集群的话 我这边暂时可能跑不了 ，您可以看下是否是redis的环境配置问题呢

**Comment by l343765828** [comment]
```
dubbo:
  scan:
    base-packages: com.testzipkin.provider.service
    # Dubbo Protocol
  protocol:
    name: dubbo
    port: -1
  registry:
    protocol: redis
    address: 192.168.3.244:32220,192.168.3.244:30256,192.168.3.244:30729
    group: dubbo
    password: 123456
    url: url
    username: name
    cluster: replicate
```
