### ISSUE TITLE
使用组播作为注册中心无法注册服务

### ISSUE THREAD

**Issue by wjzxc123** [apache/dubbo-spring-boot-project#818]
尊敬的开发者
你好

我的服务配置如下
```yaml
dubbo:
  application:
    name: ${spring.application.name}
    register-mode: instance
    qos-port: 33333
  registry:
    address: multicast://224.5.6.7:1234?unicast=false
  protocol:
    name: tri
    port: 20880
  consumer:
    check: false
    cache: false
    validation: true
    timeout: 3000
```
出现了官方文档说的 5-10 问题 
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/faq/5/10/

版本：dubbo-spring-boot-starter:3.2.0      spring-boot:2.7.2

调用该服务报错，提示No provider available for the service xxxxx
